[package]
name = "homework-2"
version = "0.1.0"
edition = "2021"
authors = ["Phisinee S. <beau.ham4t@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.4"